### ISSUE TITLE
Django integration issue

### ISSUE THREAD

**Issue by dkruk** [devkral/graphene-protector#1]
Hello! Thank you for such a useful project!

Integration with Django, which is described in the README file does not work for me, because `Graphene-Django` uses default backend instead of `ProtectorBackend`.

I fixed this by passing the backend as a view parameter. 
```path("graphql", csrf_exempt(GraphQLView.as_view(graphiql=True, backend=ProtectorBackend())))```

**Comment by devkral** [comment]
you can use the schema via 
GRAPHENE = {
    ...
    "SCHEMA": "path.to.schema",
}

there you reference the special created schema

I updated the README, hope it solves you problem
